
server:
  port: 9090

spring:
  datasource:
    username: system
    password: password
    url: jdbc:oracle:thin:@localhost:1521:xe
  #    url:  jdbc:oracle:thin:@carsnowdb_medium?TNS_ADMIN=/home/ta40463/Documents/sampleminiproj/backend/Wallet_carsNowDB
#    username: admin
#    password: CarsNow.com2021


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  io:
    swagger:
      models:
        parameters:
          AbstractSerializableParameter: error