
server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: password



  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
#      id: mobile
    client:
      client-id: mobile
      client-secret: pin


logging:
  io:
    swagger:
      models:
        parameters:
          AbstractSerializableParameter: error
